// Code generated by gtrace. DO NOT EDIT.

package trace

// persqueueComposeOptions is a holder of options
type persqueueComposeOptions struct {
	panicCallback func(e interface{})
}

// PersqueueOption specified Persqueue compose option
type PersqueueComposeOption func(o *persqueueComposeOptions)

// WithPersqueuePanicCallback specified behavior on panic
func WithPersqueuePanicCallback(cb func(e interface{})) PersqueueComposeOption {
	return func(o *persqueueComposeOptions) {
		o.panicCallback = cb
	}
}

// Compose returns a new Persqueue which has functional fields composed both from t and x.
func (t Persqueue) Compose(x Persqueue, opts ...PersqueueComposeOption) (ret Persqueue) {
	return ret
}
